import React, { useState } from 'react';
import {
  Lock,
  FileText,
  Eye,
  Download,
  CheckSquare,
  Square,
  GitCompare,
  X,
} from 'lucide-react';

const VERSIONS = ['v1.0', 'v1.1', 'v1.2', 'v1.3', 'v1.4', 'v1.5', 'v2.0'];

export default function AgreementTab() {
  const [selectedVersions, setSelectedVersions] = useState<any>([]);
  const [showCompare, setShowCompare] = useState<any>(false);

  const toggleVersion = (v : any) => {
    setShowCompare(false);
    setSelectedVersions((prev : any) => {
      if (prev.includes(v)) {
        return prev.filter((x : any) => x !== v);
      }
      if (prev.length >= 2) {
        // keep it to a pair: drop the oldest pick, add the new one
        return [prev[1], v];
      }
      return [...prev, v];
    });
  };

  const canCompare = selectedVersions.length === 2;

  const handleCompare = () => {
    if (!canCompare) return;
    setShowCompare(true);
  };

  const closeCompare = () => setShowCompare(false);

  return (
    <div className="flex flex-col gap-4">
      <div className="p-4 rounded-xl bg-slate-100 border border-slate-300 text-slate-800 font-bold text-xs flex items-center gap-2">
        <Lock className="w-4 h-4 text-slate-700" />
        <span>
          Section 11 Guard: AGREEMENT TAB IS READ-ONLY. Case Managers cannot
          edit agreement text (Constraint 3).
        </span>
      </div>

      <div className="p-5 rounded-xl bg-white border border-slate-300 flex flex-col gap-4 shadow-xs">
        <div className="flex items-center justify-between">
          <h4 className="font-bold text-xs text-slate-900 uppercase">
            Agreement Version History (Section 11)
          </h4>

          <div className="flex items-center gap-3">
            <span className="text-[10px] font-bold text-slate-500 uppercase">
              {selectedVersions.length}/2 selected
            </span>
            <button
              type="button"
              onClick={handleCompare}
              disabled={!canCompare}
              className={`text-xs font-bold px-3.5 py-1.5 rounded-lg flex items-center gap-1.5 transition-all shadow-xs active:scale-95 ${
                canCompare
                  ? 'bg-slate-900 hover:bg-slate-800 text-white cursor-pointer'
                  : 'bg-slate-200 text-slate-400 cursor-not-allowed'
              }`}
            >
              <GitCompare className="w-3.5 h-3.5" />
              Compare
            </button>
          </div>
        </div>

        <div className="flex flex-col gap-2">
          {VERSIONS.map((v : any) => {
            const isChecked = selectedVersions.includes(v);
            return (
              <div
                key={v}
                className={`p-3.5 rounded-lg bg-white border text-xs flex items-center justify-between transition-colors ${
                  isChecked
                    ? 'border-slate-500 bg-slate-50'
                    : 'border-slate-200'
                }`}
              >
                <div className="flex items-center gap-3">
                  <button
                    type="button"
                    onClick={() => toggleVersion(v)}
                    aria-label={`Select ${v} for comparison`}
                    className="cursor-pointer"
                  >
                    {isChecked ? (
                      <CheckSquare className="w-4 h-4 text-slate-900" />
                    ) : (
                      <Square className="w-4 h-4 text-slate-400" />
                    )}
                  </button>

                  <FileText className="w-4 h-4 text-slate-700" />
                  <div>
                    <span className="font-bold text-slate-900">
                      Prenuptial Agreement Draft ({v})
                    </span>
                    <span className="text-slate-400 text-[10px] block">
                      Generated by AGREEMENT_DOCUMENT_ENGINE_V1.1
                    </span>
                  </div>
                </div>

                <div className="flex items-center gap-2">
                  <button className="bg-slate-100 text-slate-800 border border-slate-300 text-xs font-bold px-3 py-1 rounded flex items-center gap-1 cursor-pointer">
                    <Eye className="w-3 h-3" /> Preview PDF
                  </button>
                  <button className="bg-slate-950 text-white text-xs font-bold px-3 py-1 rounded flex items-center gap-1 cursor-pointer">
                    <Download className="w-3 h-3" /> Download PDF
                  </button>
                </div>
              </div>
            );
          })}
        </div>
      </div>

      {/* Compare panel — appears once exactly two versions are picked and Compare is clicked */}
      {showCompare && canCompare && (
        <div className="p-5 rounded-xl bg-white border border-slate-300 flex flex-col gap-4 shadow-xs">
          <div className="flex items-center justify-between border-b border-slate-200 pb-3">
            <div className="flex items-center gap-2">
              <GitCompare className="w-4 h-4 text-slate-700" />
              <h4 className="font-bold text-xs text-slate-900 uppercase">
                Comparing {selectedVersions[0]} vs {selectedVersions[1]}
              </h4>
            </div>
            <button
              type="button"
              onClick={closeCompare}
              className="text-slate-400 hover:text-slate-700 cursor-pointer"
              aria-label="Close comparison"
            >
              <X className="w-4 h-4" />
            </button>
          </div>

          <div className="grid grid-cols-2 gap-4">
            {selectedVersions.map((v : any) => (
              <div
                key={v}
                className="border border-slate-200 rounded-lg p-3.5 flex flex-col gap-2"
              >
                <div className="flex items-center gap-2 text-xs font-bold text-slate-900">
                  <FileText className="w-3.5 h-3.5 text-slate-700" />
                  Prenuptial Agreement Draft ({v})
                </div>
                <div className="text-[11px] text-slate-500 bg-slate-50 border border-slate-200 rounded p-2.5 leading-relaxed">
                  Document body / clause diff for {v} renders here.
                </div>
              </div>
            ))}
          </div>
        </div>
      )}
    </div>
  );
}