import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";


const poppin = Poppins({
  weight : ["100","200","300","400","500","600","700","800","900"],
  subsets : ["latin"],
  variable : "--font-poppin"

})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
      cz-shortcut-listen="true"
        className={`${poppin.className} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
